### PR TITLE
Add alternative title with Eighty spelled 80

### PR DESCRIPTION
**Pull request by sylvar**
(I'm assuming that `<dc:alternate>` will get indexed by our search engine.)

### CODE REVIEW

**Comment by acabal** [comment]
I like the idea, but unfortunately we can't use `<dc:alternative>` because it is not in the list of allowed terms here: https://www.dublincore.org/specifications/dublin-core/dces/

However we may be able to further refine the `<dc:title>` element. I don't think there's an option in the epub vocabulary for what we want (`expanded` is probably closest but it's not really what we mean here) so how about we do this instead:

`<meta id="alternative-title" property="se:alternative-title" refines="#title">Around the World in 80 Days</meta>`

**Comment by sylvar** [comment]
Sounds good to me. Thank you for the explanation. Is it good form for me to
edit my patch or would it be better for me to do something else?

**Comment by acabal** [comment]
You can just edit you patch. Thanks!

**Comment by sylvar** [comment]
OK, I think I just did. Thanks!

**Comment by acabal** [comment]
Great, thanks!

**Pull request merged**
